server:
  port: 8888
spring:
  mail:
    host: smtp.163.com
    username: 18160787649@163.com
    password: PWINMOYTJQRDDOZV
  datasource:
    username: root
    password: abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
