server:
  port: 8888
spring:
  mail:
    host: smtp.163.com
    username: 18160787649@163.com
    password: PWINMOYTJQRDDOZV
  # mysql 配置
  datasource:
    username: root
    password: fuckoff
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.163.10:3306/blog_data?characterEncoding=UTF-8
    hikari:
      connection-test-query: "select 1"
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  # redis 配置
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
      password:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8